## prework

* import basic dependencies
* load data
* check data

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/mnist-numpy/mnist.npz


In [2]:
from keras.datasets import mnist

# load data
(X_train, y_train), (X_test, y_test) = mnist.load_data()

11493376/11490434 [==============================] - 0s 0us/step


In [3]:
path = '/kaggle/input/mnist-numpy/mnist.npz'
f = np.load(path)
train_images, train_labels = f['x_train'], f['y_train']
test_images, test_labels = f['x_test'], f['y_test']
f.close()

## Data Preprocessing

* reshape
* transform data type
* normalization
* label => one-hot encoding

In [4]:
from keras.utils import to_categorical

In [5]:
# reshape
X_train = X_train.reshape([60000, 784])
X_test = X_test.reshape([10000, 784])
X_train.shape, X_test.shape

((60000, 784), (10000, 784))

In [6]:
# transform np data type
X_train = X_train.astype(np.float32)
X_test = X_test.astype(np.float32)

In [7]:
# normalization
X_train = X_train/255
X_test = X_test/255
print(X_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [8]:
# one-hot encoding
train_labels = to_categorical(y_train)
test_labels = to_categorical(y_test)

## Model

* build model
* compile, summary
* fit, evaluate

</br></br>

* advanced NN model

In [9]:
from keras.models import Sequential
from keras.layers import Dense, Activation

In [10]:
# build simple model
model = Sequential()
model.add(Dense(10, input_shape=(28*28, )))
model.add(Activation('softmax'))

In [11]:
# compile
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])
# summary
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                7850      
_________________________________________________________________
activation (Activation)      (None, 10)                0         
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________


In [12]:
# fit
model.fit(X_train, train_labels, epochs=200, batch_size=128, verbose=True, validation_split=0.2)

Epoch 1/200
375/375 [==============================] - 1s 3ms/step - loss: 1.3824 - accuracy: 0.6680 - val_loss: 0.8981 - val_accuracy: 0.8270
Epoch 2/200
375/375 [==============================] - 1s 3ms/step - loss: 0.7923 - accuracy: 0.8297 - val_loss: 0.6586 - val_accuracy: 0.8564
Epoch 3/200
375/375 [==============================] - 1s 3ms/step - loss: 0.6419 - accuracy: 0.8510 - val_loss: 0.5625 - val_accuracy: 0.8705
Epoch 4/200
375/375 [==============================] - 1s 2ms/step - loss: 0.5695 - accuracy: 0.8614 - val_loss: 0.5095 - val_accuracy: 0.8783
Epoch 5/200
375/375 [==============================] - 1s 2ms/step - loss: 0.5254 - accuracy: 0.8682 - val_loss: 0.4756 - val_accuracy: 0.8823
Epoch 6/200
375/375 [==============================] - 1s 2ms/step - loss: 0.4953 - accuracy: 0.8734 - val_loss: 0.4514 - val_accuracy: 0.8863
Epoch 7/200
375/375 [==============================] - 1s 2ms/step - loss: 0.4730 - accuracy: 0.8776 - val_loss: 0.4332 - val_accuracy: 0.8894

In [13]:
# evaluate
test_loss, test_acc = model.evaluate(X_test, test_labels, verbose=True)
print('test_loss', test_loss, '\n', 'test_acc', test_acc)

313/313 [==============================] - 1s 2ms/step - loss: 0.2775 - accuracy: 0.9228
test_loss 0.2774983048439026 
 test_acc 0.9228000044822693


In [14]:
# advanced NN model
model = Sequential()
model.add(Dense(128, input_shape=(28*28, ),activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

In [15]:
# compile
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])
# summary
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 128)               100480    
_________________________________________________________________
dense_2 (Dense)              (None, 128)               16512     
_________________________________________________________________
dense_3 (Dense)              (None, 10)                1290      
Total params: 118,282
Trainable params: 118,282
Non-trainable params: 0
_________________________________________________________________


In [16]:
# fit
model.fit(X_train, train_labels, epochs=200, batch_size=128, verbose=True, validation_split=0.2)

Epoch 1/200
375/375 [==============================] - 1s 3ms/step - loss: 1.4514 - accuracy: 0.6569 - val_loss: 0.7409 - val_accuracy: 0.8436
Epoch 2/200
375/375 [==============================] - 1s 3ms/step - loss: 0.5846 - accuracy: 0.8572 - val_loss: 0.4451 - val_accuracy: 0.8850
Epoch 3/200
375/375 [==============================] - 1s 3ms/step - loss: 0.4299 - accuracy: 0.8837 - val_loss: 0.3683 - val_accuracy: 0.8975
Epoch 4/200
375/375 [==============================] - 1s 3ms/step - loss: 0.3734 - accuracy: 0.8955 - val_loss: 0.3316 - val_accuracy: 0.9060
Epoch 5/200
375/375 [==============================] - 1s 3ms/step - loss: 0.3416 - accuracy: 0.9035 - val_loss: 0.3087 - val_accuracy: 0.9108
Epoch 6/200
375/375 [==============================] - 1s 3ms/step - loss: 0.3195 - accuracy: 0.9091 - val_loss: 0.2920 - val_accuracy: 0.9142
Epoch 7/200
375/375 [==============================] - 1s 3ms/step - loss: 0.3022 - accuracy: 0.9136 - val_loss: 0.2786 - val_accuracy: 0.9195

In [17]:
# evaluate
test_loss, test_acc = model.evaluate(X_test, test_labels, verbose=True)
print('test_loss', test_loss, '\n', 'test_acc', test_acc)

313/313 [==============================] - 1s 2ms/step - loss: 0.0775 - accuracy: 0.9766
test_loss 0.07749566435813904 
 test_acc 0.9765999913215637


### Advanced CNN

In [18]:
# reshape
X_train = X_train.reshape(-1, 28, 28, 1)
X_test = X_test.reshape(-1, 28, 28, 1)

In [19]:
from keras.layers import Conv2D, BatchNormalization, Dropout, Conv2D, MaxPool2D, Conv2D, Flatten, Dense
from keras.optimizers import Adam

In [20]:
# build advanced advanced CNN model
model = Sequential()
model.add(Conv2D(filters=32, kernel_size=(3, 3), padding='Same', activation='relu', input_shape=(28, 28, 1)))
# add two layers => avoid overfit
model.add(BatchNormalization(axis=1)) 
model.add(Dropout(0.5))
model.add(Conv2D(filters=32, kernel_size=(3, 3), padding='Same', activation='relu', input_shape=(28, 28, 1)))
model.add(BatchNormalization(axis=1)) 

model.add(MaxPool2D(pool_size=(2, 2)))

model.add(Conv2D(filters=64, kernel_size=(3, 3), padding='Same', activation='relu'))
model.add(BatchNormalization(axis=1)) 
model.add(Dropout(0.5))
model.add(Conv2D(filters=64, kernel_size=(3, 3), padding='Same', activation='relu'))
model.add(MaxPool2D(pool_size=(2, 2)))

model.add(Flatten())
model.add(BatchNormalization()) 
model.add(Dropout(0.5))
model.add(Dense(512, activation='relu'))
model.add(BatchNormalization()) 
model.add(Dropout(0.5))
model.add(Dense(10, activation='softmax'))

In [21]:
# compile
model.compile(Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
# summary
model.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 28, 28, 32)        320       
_________________________________________________________________
batch_normalization (BatchNo (None, 28, 28, 32)        112       
_________________________________________________________________
dropout (Dropout)            (None, 28, 28, 32)        0         
_________________________________________________________________
conv2d_1 (Conv2D)            (None, 28, 28, 32)        9248      
_________________________________________________________________
batch_normalization_1 (Batch (None, 28, 28, 32)        112       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 14, 14, 32)        0         
_________________________________________________________________
conv2d_2 (Conv2D)            (None, 14, 14, 64)       

In [22]:

model.fit(X_train, train_labels, epochs=15, batch_size=128, verbose=True, validation_split=0.1)

Epoch 1/15
422/422 [==============================] - 5s 11ms/step - loss: 0.3526 - accuracy: 0.8938 - val_loss: 1.3417 - val_accuracy: 0.5328
Epoch 2/15
422/422 [==============================] - 4s 11ms/step - loss: 0.1087 - accuracy: 0.9659 - val_loss: 0.0696 - val_accuracy: 0.9795
Epoch 3/15
422/422 [==============================] - 4s 10ms/step - loss: 0.0778 - accuracy: 0.9751 - val_loss: 0.0569 - val_accuracy: 0.9835
Epoch 4/15
422/422 [==============================] - 4s 10ms/step - loss: 0.0616 - accuracy: 0.9797 - val_loss: 0.0388 - val_accuracy: 0.9880
Epoch 5/15
422/422 [==============================] - 4s 10ms/step - loss: 0.0577 - accuracy: 0.9824 - val_loss: 0.0426 - val_accuracy: 0.9878
Epoch 6/15
422/422 [==============================] - 4s 10ms/step - loss: 0.0504 - accuracy: 0.9840 - val_loss: 0.0437 - val_accuracy: 0.9865
Epoch 7/15
422/422 [==============================] - 5s 11ms/step - loss: 0.0487 - accuracy: 0.9849 - val_loss: 0.0323 - val_accuracy: 0.9910

In [23]:
# evaluate
test_loss, test_acc = model.evaluate(X_test, test_labels, verbose=True)
print('test_loss', test_loss, '\n', 'test_acc', test_acc)

313/313 [==============================] - 1s 3ms/step - loss: 0.0223 - accuracy: 0.9932
test_loss 0.02232465147972107 
 test_acc 0.9932000041007996


### Add image_generator for data augmentation

In [24]:
from keras.preprocessing.image import ImageDataGenerator

In [25]:
generator = ImageDataGenerator(rotation_range=10, width_shift_range=0.10, shear_range=0.5, height_shift_range=0.10, zoom_range=0.10)
# compile model with data generator
model.compile(Adam(), loss='categorical_crossentropy', metrics=['accuracy'])
model.optimizer.lr=0.001
batches = generator.flow(X_train, train_labels, batch_size=128)

In [26]:
# fit
%time history = model.fit_generator(generator=batches, steps_per_epoch=batches.n, epochs=15)

Epoch 1/15
  469/60000 [..............................] - 23s 49ms/step - loss: 0.1087 - accuracy: 0.9671
CPU times: user 26.7 s, sys: 526 ms, total: 27.2 s
Wall time: 24.4 s


In [27]:
# evaluate
test_loss, test_acc = model.evaluate(X_test, test_labels, verbose=True)
print('test_loss', test_loss, '\n', 'test_acc', test_acc)

313/313 [==============================] - 1s 3ms/step - loss: 0.0162 - accuracy: 0.9939
test_loss 0.016232000663876534 
 test_acc 0.9939000010490417
