## prework

* import basic dependencies
* load data
* check data

In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/mnist-numpy/mnist.npz


In [2]:
from keras.datasets import mnist

# load data
(X_train, y_train), (X_test, y_test) = mnist.load_data()


11493376/11490434 [==============================] - 0s 0us/step


In [3]:
path = '/kaggle/input/mnist-numpy/mnist.npz'
f = np.load(path)
train_images, train_labels = f['x_train'], f['y_train']
test_images, test_labels = f['x_test'], f['y_test']
f.close()

## Data Preprocessing

* reshape
* transform data type
* normalization
* label => one-hot encoding

In [4]:
from keras.utils import to_categorical

In [5]:
# reshape
X_train = X_train.reshape([60000, 784])
X_test = X_test.reshape([10000, 784])
X_train.shape, X_test.shape

((60000, 784), (10000, 784))

In [6]:
# transform np data type
X_train = X_train.astype(np.float32)
X_test = X_test.astype(np.float32)

In [7]:
# normalization
X_train = X_train/255
X_test = X_test/255
print(X_train)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [8]:
# one-hot encoding
train_labels = to_categorical(y_train)
test_labels = to_categorical(y_test)

## Model

* build model
* compile, summary
* fit, evaluate

</br></br>

* advanced NN model

In [9]:
from keras.models import Sequential
from keras.layers import Dense, Activation

In [10]:
# build simple model
model = Sequential()
model.add(Dense(10, input_shape=(28*28, )))
model.add(Activation('softmax'))

In [11]:
# compile
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])
# summary
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 10)                7850      
_________________________________________________________________
activation (Activation)      (None, 10)                0         
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________


In [12]:
# fit
model.fit(X_train, train_labels, epochs=200, batch_size=128, verbose=True, validation_split=0.2)

Epoch 1/200
375/375 [==============================] - 1s 3ms/step - loss: 1.4146 - accuracy: 0.6566 - val_loss: 0.9018 - val_accuracy: 0.8327
Epoch 2/200
375/375 [==============================] - 1s 3ms/step - loss: 0.7961 - accuracy: 0.8296 - val_loss: 0.6589 - val_accuracy: 0.8593
Epoch 3/200
375/375 [==============================] - 1s 2ms/step - loss: 0.6441 - accuracy: 0.8511 - val_loss: 0.5617 - val_accuracy: 0.8732
Epoch 4/200
375/375 [==============================] - 1s 2ms/step - loss: 0.5712 - accuracy: 0.8624 - val_loss: 0.5091 - val_accuracy: 0.8784
Epoch 5/200
375/375 [==============================] - 1s 2ms/step - loss: 0.5269 - accuracy: 0.8688 - val_loss: 0.4745 - val_accuracy: 0.8849
Epoch 6/200
375/375 [==============================] - 1s 3ms/step - loss: 0.4966 - accuracy: 0.8747 - val_loss: 0.4503 - val_accuracy: 0.8883
Epoch 7/200
375/375 [==============================] - 1s 3ms/step - loss: 0.4742 - accuracy: 0.8787 - val_loss: 0.4322 - val_accuracy: 0.8905

In [13]:
# evaluate
test_loss, test_acc = model.evaluate(X_test, test_labels, verbose=True)
print('test_loss', test_loss, '\n', 'test_acc', test_acc)

313/313 [==============================] - 1s 2ms/step - loss: 0.2771 - accuracy: 0.9222
test_loss 0.2770804762840271 
 test_acc 0.9222000241279602


In [14]:
# advanced NN model
model = Sequential()
model.add(Dense(128, input_shape=(28*28, ),activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dense(10, activation='softmax'))

In [15]:
# compile
model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])
# summary
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 128)               100480    
_________________________________________________________________
dense_2 (Dense)              (None, 128)               16512     
_________________________________________________________________
dense_3 (Dense)              (None, 10)                1290      
Total params: 118,282
Trainable params: 118,282
Non-trainable params: 0
_________________________________________________________________


In [16]:
# fit
model.fit(X_train, train_labels, epochs=200, batch_size=128, verbose=True, validation_split=0.2)

Epoch 1/200
375/375 [==============================] - 1s 3ms/step - loss: 1.4005 - accuracy: 0.6588 - val_loss: 0.7020 - val_accuracy: 0.8391
Epoch 2/200
375/375 [==============================] - 1s 3ms/step - loss: 0.5723 - accuracy: 0.8541 - val_loss: 0.4464 - val_accuracy: 0.8794
Epoch 3/200
375/375 [==============================] - 1s 2ms/step - loss: 0.4294 - accuracy: 0.8817 - val_loss: 0.3697 - val_accuracy: 0.8958
Epoch 4/200
375/375 [==============================] - 1s 3ms/step - loss: 0.3736 - accuracy: 0.8945 - val_loss: 0.3363 - val_accuracy: 0.9052
Epoch 5/200
375/375 [==============================] - 1s 2ms/step - loss: 0.3420 - accuracy: 0.9026 - val_loss: 0.3105 - val_accuracy: 0.9107
Epoch 6/200
375/375 [==============================] - 1s 2ms/step - loss: 0.3200 - accuracy: 0.9083 - val_loss: 0.2934 - val_accuracy: 0.9168
Epoch 7/200
375/375 [==============================] - 1s 3ms/step - loss: 0.3030 - accuracy: 0.9131 - val_loss: 0.2807 - val_accuracy: 0.9205

In [17]:
# evaluate
test_loss, test_acc = model.evaluate(X_test, test_labels, verbose=True)
print('test_loss', test_loss, '\n', 'test_acc', test_acc)

313/313 [==============================] - 1s 2ms/step - loss: 0.0810 - accuracy: 0.9764
test_loss 0.08096080273389816 
 test_acc 0.9764000177383423
